version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    volumes: 
      - ./:/backstage-frontend/
    ports:
      - "3000:3000"
    restart: always
    command: "yarn start"
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    volumes:
      - ./:/backstage-backend/
    restart: always
    expose:
      - "7000"
    command: "yarn start"